name: Build

on:
  push:
    branches: [dev, main, '**' ]
  pull_request:
    branches: [dev, main ]
    
jobs:

  ubuntu:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .Net SDK 6.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
          
      - name: Show dotnet Version
        run: |
          dotnet --list-sdks
          dotnet --list-runtimes
      
      - name: Build with dotnet
        run: |
          dotnet build --configuration Release Libraries.sln
