name: Build&Test

on:
  push:
    branches: [dev, main, master, '**' ]
  pull_request:
    branches: [dev, main, master]
    
jobs:

  linux:
    name: build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    
    services:
      redis6379:
        image: redis
        ports:
         - 6379:6379
      redis6380:
        image: redis
        ports:
         - 6380:6379
      redis6388:
        image: redis
        ports:
           - 6388:6379     
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .Net SDK 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          
      - name: Show dotnet Version
        run: |
          dotnet --list-sdks
          dotnet --list-runtimes
      
      - name: Show docker info
        run: |
          docker ps -a   
      
      - name: Build with dotnet
        run: |
          dotnet build --configuration Release Libraries.sln
          
      - name: Run tests on net 6.0
        run: |
          dotnet test --framework=net6.0 Libraries.sln
